### ISSUE TITLE
ServiceBot set-up makes request to non-existent URL

### ISSUE THREAD

**Issue by sjlongland** [service-bot/servicebot#299]
When configuring ServiceBot in either Firefox 57 or Chromium 63, the set-up fails with the message "There seems to be a problem in processing your request. Please try again.".  Trying again does nothing.

Deployed instance for trial of ServiceBot:
* https://widesky.vrtaws.vk4msl.id.au

Deployment details:
* Kubernetes 1.8.6 on Amazon AWS
* ServiceBot is behind a nginx reverse proxy with the following configuration
```
server {
    listen 443 ssl;
ssl_certificate_key /var/local/letsencrypt/live/widesky.vrtaws.vk4msl.id.au/privkey.pem;
ssl_certificate /var/local/letsencrypt/live/widesky.vrtaws.vk4msl.id.au/fullchain.pem;
    server_name widesky.vrtaws.vk4msl.id.au;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    include /etc/nginx/conf.d/default-locations/*.conf;
# /etc/nginx/conf.d/default-locations/*.conf content
# Remote mount point 0: http://servicebot:3000/ -> /
# Generated by /usr/local/sbin/docker-entrypoint.sh: pid 1
location / {
    proxy_pass http://servicebot:3000/;
}
# end /etc/nginx/conf.d/default-locations/*.conf content

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listen 443 ssl;
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listen 443 ssl;
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```

Logs from console (Firefox):
```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
bundle.js:99449:9
GETTIN PLUGIN! core-input-types
bundle.js:124812:37
THIS IS PLUGIN 
Object { run: run() }
bundle.js:124817:37
GETTIN PLUGIN! ga
bundle.js:124812:37
THIS IS PLUGIN 
Object { run: run(), … }
bundle.js:124817:37
 action  PLUGIN_ENABLED  @ 15:57:30.527
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "PLUGIN_ENABLED", plugin: {…}, … }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
Download the React DevTools for a better development experience: https://fb.me/react-devtools
core-input-types.js:16765:9
 action  PLUGIN_ENABLED  @ 15:57:30.572
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "PLUGIN_ENABLED", plugin: {…}, … }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
 action  SERVICE_PROVIDED  @ 15:57:30.575
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "SERVICE_PROVIDED", serviceType: "widget", service: {…}, provider: undefined, ephemeral: false, … }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
 action  SERVICE_PROVIDED  @ 15:57:30.576
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "SERVICE_PROVIDED", serviceType: "widget", service: {…}, provider: undefined, ephemeral: false, … }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
 action  SERVICE_PROVIDED  @ 15:57:30.576
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "SERVICE_PROVIDED", serviceType: "widget", service: {…}, provider: undefined, ephemeral: false, … }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
 action  SERVICE_PROVIDED  @ 15:57:30.577
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "SERVICE_PROVIDED", serviceType: "widget", service: {…}, provider: undefined, ephemeral: false, … }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
 action  @@router/LOCATION_CHANGE  @ 15:57:30.589
bundle.js:124727:5935
 prev state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6174
 action     
Object { type: "@@router/LOCATION_CHANGE", payload: {…} }
bundle.js:124727:6294
 next state 
Object { allForms: {}, options: {}, notifications: [], system_notifications: [], alerts: [], uid: null, permissions: [], user: {}, form: {}, routing: {…}, … }
bundle.js:124727:6544
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 
function Route()
bundle.js:94487:5
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 
function Router()
bundle.js:94487:5
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 
function RouterContext()
bundle.js:94487:5
Unhandled promise rejection 
Response { type: "basic", url: "https://widesky.vrtaws.vk4msl.id.au/api/v1/system-options/public", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers, bodyUsed: false }
bundle.js:110572:11
onUnhandled/</result<
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:110572:11
module.exports
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:67458:27
onUnhandled/<
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:110566:16
module.exports
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:110819:25
<anonymous>
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:67394:7
run
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:67380:5
listener
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:67384:3
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 
function Link()
bundle.js:94487:5
Warning: SetupStripe is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
bundle.js:33655:7
Proxy { <target>: {…}, <handler>: {…} }
bundle.js:186730:17
handleSubmit
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:186730:17
proxiedMethod
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:98272:16
boundFunc
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:55024:9
ReactErrorUtils.invokeGuardedCallback
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:55030:7
executeDispatch
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:54814:5
executeDispatchesInOrder
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:54837:5
executeDispatchesAndRelease
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:45258:5
executeDispatchesAndReleaseTopLevel
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:45269:10
forEachAccumulated
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:64696:5
processEventQueue
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:45469:7
runEventQueueInBatch
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:103668:3
handleTopLevel
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:103678:5
handleTopLevelImpl
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:106922:5
perform
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:49728:13
batchedUpdates
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:106841:14
batchedUpdates
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:38670:10
dispatchEvent
https://widesky.vrtaws.vk4msl.id.au/build/bundle.js:106997:7
unreachable code after return statement
[Learn More]
bundle.js:181460:28
Source map error: request failed with status 404
Resource URL: https://widesky.vrtaws.vk4msl.id.au/build/bundle.js
Source Map URL: es6-promise.map
[Learn More]
```

**Comment by bsears90** [comment]
What does your deployment look like? I run a very similar setup with Kubernetes.

**Comment by sjlongland** [comment]
As I say, not very complicated; just a `nginx` front-end proxy pointed at ServiceBot (private image on Docker Hub; it generated the above `nginx` config).  The container we use for the front-end proxy takes care of Let's Encrypt registration.  The deployment script was generated from a tweaked (by adding the reverse proxy) `docker-compose.yml` file, then converted using `kompose`.

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kompose.yml -f docker-compose.yaml
      kompose.version: 1.8.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: db
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kompose.yml -f docker-compose.yaml
      kompose.version: 1.8.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: nginx
    name: nginx
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    type: LoadBalancer
    selector:
      io.kompose.service: nginx
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kompose.yml -f docker-compose.yaml
      kompose.version: 1.8.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: servicebot
    name: servicebot
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: servicebot
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kompose.yml -f docker-compose.yaml
      kompose.version: 1.8.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
      spec:
        containers:
        - env:
          - name: POSTGRES_DB
            value: 'xxxxxxxx'
          - name: POSTGRES_PASSWORD
            value: 'xxxxxxxx'
          - name: POSTGRES_USER
            value: 'xxxxxxxx'
          image: postgres:latest
          name: db
          resources: {}
        restartPolicy: Always
        imagePullSecrets:
        - name: regcred
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kompose.yml -f docker-compose.yaml
      kompose.version: 1.8.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: nginx
    name: nginx
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: nginx
      spec:
        containers:
        - env:
          - name: CERT_TYPE
            value: le
          - name: LETS_ENCRYPT_ADMIN
            value: softeng@vrt.com.au
          - name: MOUNT_DEST0
            value: /
          - name: MOUNT_SRC0
            value: http://servicebot:3000/
          - name: SECURE_REDIRECT
            value: "TRUE"
          - name: SERVER_NAME
            value: widesky.vrtaws.vk4msl.id.au
          image: vrtsystems/widesky-nginx:develop
          name: nginx
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
          volumeMounts:
          - mountPath: /var/local
            name: nginx-data
        restartPolicy: Always
        imagePullSecrets:
        - name: regcred
        volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: nginx-data
    name: nginx-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kompose.yml -f docker-compose.yaml
      kompose.version: 1.8.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: servicebot
    name: servicebot
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: servicebot
      spec:
        containers:
        - args:
          - sh
          - -c
          - node /usr/src/app/bin/wait-for-it.js db 5432  && npm run-script start
          env:
          - name: PORT
            value: '3000'
          - name: POSTGRES_DB_HOST
            value: 'db'
          - name: POSTGRES_DB_NAME
            value: 'xxxxxxxx'
          - name: POSTGRES_DB_PASSWORD
            value: 'xxxxxxxx'
          - name: POSTGRES_DB_PORT
            value: '5432'
          - name: POSTGRES_DB_USER
            value: 'xxxxxxxx'
          image: servicebot/servicebot
          name: servicebot
          resources: {}
          volumeMounts:
          - mountPath: /usr/src/app/uploads
            name: upload-data
          - mountPath: /usr/src/app/env
            name: environment-file
        restartPolicy: Always
        imagePullSecrets:
        - name: regcred
        volumes:
        - name: upload-data
          persistentVolumeClaim:
            claimName: upload-data
        - name: environment-file
          persistentVolumeClaim:
            claimName: environment-file
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: upload-data
    name: upload-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: environment-file
    name: environment-file
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}
```
